"""empty message

Revision ID: 5b1ef7924cea
Revises: 422440082deb
Create Date: 2026-07-16 21:26:10.429016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1ef7924cea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('event_id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('operation_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('event_type', sa.Enum('CREATED', 'SUBMIT_REQUESTED', 'CALLBACK_RECEIVED',
                                                    'PROVIDER_RESPONSE_RECEIVED', name='eventtype'), nullable=False),
                    sa.Column('from_status', sa.Enum('CREATED', 'PROCESSING',
                                                     'COMPLETED', 'REJECTED', name='operationstatus'), nullable=True),
                    sa.Column('to_status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED',
                                                   'REJECTED', name='operationstatus'), nullable=False),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('occurred_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('event_id'),
                    sa.UniqueConstraint('operation_id', 'event_type',
                                        'to_status', name='uq_operation_event_transition')
                    )
    op.create_table('operations',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('amount', sa.DECIMAL(
                        precision=19, scale=2), nullable=False),
                    sa.Column('currency', sa.String(length=3), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED',
                                                'REJECTED', name='operationstatus'), nullable=False),
                    sa.Column('provider_payment_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('processed_callbacks',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('provider_payment_id',
                              sa.UUID(), nullable=False),
                    sa.Column('operation_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('result', sa.Enum('COMPLETED', 'REJECTED',
                                                name='callbackresult'), nullable=False),
                    sa.Column('processed_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('provider_payment_id',
                                        'operation_id', name='uq_processed_callback')
                    )
    op.create_table('submit_intents',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('operation_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING',
                                                'COMPLETED', 'FAILED', name='intentstatus'), nullable=False),
                    sa.Column('attempt_count', sa.Integer(), nullable=False),
                    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'operation_id', name='uq_submit_intent_operation')
                    )
    op.create_index('idx_intents_pending', 'submit_intents', [
                    'status', 'next_retry_at'], unique=False, postgresql_where="status IN ('PENDING', 'FAILED')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_intents_pending', table_name='submit_intents',
                  postgresql_where="status IN ('PENDING', 'FAILED')")
    op.drop_table('submit_intents')
    op.drop_table('processed_callbacks')
    op.drop_table('operations')
    op.drop_table('events')
    # ### end Alembic commands ###
